[webservers]web-1 ansible_host=111.88.255.88 fqdn=fhmi2n9dp2g61bepe7fe.auto.internalweb-2 ansible_host=111.88.242.53 fqdn=fhmk80eh24v381fso194.auto.internal
[databases]main ansible_host= fqdn=fhm1pa77t93dql3hmkuk.auto.internalreplica ansible_host= fqdn=fhm7e3sjr7hququs1cms.auto.internal
[storage]storage ansible_host=111.88.247.251 fqdn=fhmou8nspveerko92mkl.auto.internal
